version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID:  17809227
      API_HASH: 24c6288eee3e68db783afaf3df669534
      BOT_TOKEN: 5105784060:AAEuQbnUpzwHslcL_cyoArS5F1Q2IVtN_Qk 
      SESSION: BQAv3AV1FipqJcAAZ0VMwrOH-8MaBt07cSOswapa24CdPa1TcYJxRpZw1PB_K89vqpGJHMI4jl5p95-qQ7trrbpblI0scwlnZehK5h1Wfb9yKVIeh3TJaEM39nGLKEUAEh3rIaRYwOvBQNbDe-bq5-XHnakL1pF2TnL-GSv9h4sjnA-45G1OZnuoO2256k4cr45tO96K1SZr1PAeW5tqCP9w-tBGGNvBODxyh1kfJB9xRSjaGFyzq7rR9dvrOgveO6OP6TMMAdJf-aimf1SoOLt3U7LonX-jCRfhv_qYN2FW4032QVcns-qoCW3uOtZdUJRy8Ze56kPXtHXKXMXBWsJXVFY_KAA
      AUTH: 1414938408
      FORCESUB: safalam_clssses